### ISSUE TITLE
rclip in FreeBSD

### ISSUE THREAD

**Issue by maurizio-emmex** [noboruma/rclip#1]
I have successfully installed rclip in FreeBSD, but I can't run it with  open argument :
```
$HOME/.cargo/bin/rclip open
RCLIP_URL variable is missing from the config file.
Please look at: https://github.com/noboruma/rclip-backends to setup your own secure backend
WARNING: rclip will use a default unsecured backend, your data might be accessed publicly
error: Failed to use clipboard with the backend (Is it opened/linked?)
```
The same happens running  the link command  with a valid hash.

Thanks for your work
Maurizio

**Comment by noboruma** [comment]
Hello Maurizio,

Can you please switch to the `wasm` branch and give it a try?
I have rework the way the back-end is interacting with the client, I have not find time to merge it to `master` yet.

Also, please make sure your `RCLIP_URL` parameter is set.
You can do this by having a file in `~/.rclip.env` and have:
```
RCLIP_URL=https://aws.remote-clipboard.net/
```

Please let me know how that goes

**Comment by maurizio-emmex** [comment]
Hello Thomas,
now it works in FreeBSD, but I have found a new issue in Windows 10.
Thank you 
Maurizio
